### ISSUE TITLE
animations are slow on nexus 5.

### ISSUE THREAD

**Issue by abacaj** [reapp/reapp#18]
Don't know why but the off-canvas menu and the full-page sliding effect is slow as hell.

If this is JavaScript based animation, it shouldn't be this slow.

**Comment by natew** [comment]
Hasn't been tested yet on nexus but you're right. Last I checked it on a nexus it was smooth so something may have changed.

**Comment by natew** [comment]
Which page slide effect are you seeing slow? In the kitchen sink app or HN? We've done some optimizations on both, but I need to grab an android to test it out soon.

**Comment by landabaso** [comment]
Hi natew, I've been testing on an "old" iphone 4 running iOS 7.1.2 and animations when changing views in kitchen sink are also super slow. 
Is that expected behaviour for such device or there's maybe a quick fix that may improve it? Apart form that reapp looks promising. Good job!

**Comment by natew** [comment]
We're working on it. Actually just earlier today we landed a big performance patch, update reapp-UI. It hasn't landed yet on the kitchen sink demo, I'll deploy it tomorrow.

**Comment by natew** [comment]
Another big performance patch landed. In the craziness of releasing all the modules I shuffled out the requestAnimationFrame rendering strategy for React... duh.

That, and another Scroller performance fix has brought some pretty big improvements. Just tested the kitchen sink demo though and we're getting flickering at least in one case.

That said, I'm pretty happy. We've done only one week of performance optimization and already seen huge benefits. And now have lots of ideas for further improvement.

**Comment by romanonthego** [comment]
View changing animation is noticeably slow on iphone 5 with ios 8.2.
I've made a video to show it but on video it actually a MUCH smoother than on device itself. (kitchen sink and hn app have very same issue actually). See for yourself  - [video](https://dl.dropboxusercontent.com/u/32370451/reapp%20slow%20animation.mov)

off-canvas menu animation however is very sleek and close to 60fps.
reapp-ui version is 0.10.16 and reapp version is 0.8.3.

**Comment by natew** [comment]
@romanonthego that animation actually doesn't look bad. It actually is timed much slower (500ms vs 300ms) than the menu animation.

I do see a very slight frame drop, but it's really more the slow speed of the animation than actual lag.

In iOS the forward animation is 500ms, while the backward one is closer to 400. I have a ticket to make the scroller more flexible, but I need to write that in. It shouldn't be hard but basically we need an interface to make the scroller speed changeable so when going forward we do 500, but backward 400. This is coming up soon.

**Comment by natew** [comment]
That said, there is some slight frame dropping going on there. We've implemented context based animations I'd be curious to see how they perform on the 5 now. I also have a tweak that does the non-interactive animations more smoothly that I want to release soon.

In any case, I am a little frustrated with the speed. It shouldn't be a problem handling those animations. They are doing some complex stuff. For example

1. the ViewList runs the Scroller, renders on each frame
2. Viewlist clones each View on each frame
3. Each view renders TitleBar
4. Renders Button
5. Renders Icon

This is a big render tree for animations on mobile. I actually had a huge rewrite I spent a week on a long while ago to run animations outside of the render() tree in React. What was funny is it actually went slower than the React version. I think it was just my implementation. I'd love some help on this, but I will continue to push on it and I still think a separate, context-based pipeline that avoids renders would be awesome. It would require patching React itself, but I am going to explore it in the next couple months.

**Comment by romanonthego** [comment]
as i said - it's actually a lot smoother on video for some reason (it's feels like 2x devise fps - i've recorded it via quicktime from mac os). Slowdown is not unusable but still obliviously noticeable.
I understand the length you have to go to bring almost native interaction on web soil, now I just wondering if it's actually as good as it's gets without reinventing react from scratch (it would be nice to have custom interceptors in DOM diff algorithm). Maybe it is part of the reason they bring react native into play - as they said at the video - JS and DOM are not fast enough for this sleek-and-sexy animation and gesture-based interaction, no matter how hard you try.

Reapp is still the best way to bootstrap an hybrid app i've found, so thanks :)

**Comment by natew** [comment]
It's definitely possible. Check out framework7. The problem is running through react. In 0.14 they are adding more optimization to static nodes which should bring a big boost for this specific example. And I won't stop pushing. 

Again this is an edge case. It's deeply nested components with multiple animations. And it runs smooth on iPhone 6 and even iPhone 5 once it's bundled as an app. That impressive considering I've only been optimizing it for less than a month!

**Comment by nolimits4web** [comment]
@natew still can't find more time to contribute to reapp, but here is a good tip to you. 
Totally, absolutely totally remove "box-shadow" and its animation/transition from views and during "swipe back". I have replaced it with pseudo elements with gradients, you may check how it is now in F7. But removing box-shadow gave me just a huge performance boost in transitions and animations ;)

**Comment by natew** [comment]
@nolimits4web thanks for the tip! I noticed when I was animating the box-shadow (changing the rgba value on animations) it was repainting on every frame which was killing performance, but I stopped animating it and just have it static, which prevented repaints.

I'll try out removing the box shadow altogether! I thought because it wasn't repainting that fixed it but appreciate the tip. Framework7 was a big help when building reapp, I admire the work thats gone into it.

**Comment by nolimits4web** [comment]
Thanks. I also have tried on just stopping to animate it, but doesn't help a lot. The problem seems to be (at least in iOS) is that when we have box-shadow on such complex element as View with complex DOM structure inside, then for some reasons it take a lot of time/efforts to render it, don't fully understand why. Also, after removing box-shadow, the DOM of just loaded pages began to render much faster, and a lot of other rendering issues just gone. So try to totally remove/replace it

**Comment by natew** [comment]
I pushed up a new version of reapp-ui `0.11.13` that uses a separate shadow div rather than box-shadow. I see nicely improved performance. Also built a new version of Kitchen Sink that uses it. Simplifies quite a few things!

On my old android phone though it's still slow. Need to get an iPhone 5 to test on as well which I'm in the process of getting.

cc @nolimits4web

**Comment by chenglou** [comment]
Hey! Just read through this thread. A few thoughts:

1. Can you clarify on how you use context to make animation work better? (Btw context is becoming parent-based. Hope you knew that).

2. Performant nested animation and others are tricky, yeah. Putting `shouldComponentUpdate` and disabling the whole subtree during animation (that's what fb did for some components that use rAF + render) should help a lot here, but it's situation-specific.

3. Compiling to CSS/precomputing values gets tricky. I assume you mean transforming your declarations from repeated renders to CSS animations to avoid renders (if not, then I'm not sure what you mean). It's error-prone (e.g. expecting a render but it turned into CSS animation because of some other part of the code. Better off just using the previous `shouldComponentUpdate` strategy). You lose so much expressive power that you might be better off just writing the CSS transitions manually. You use JS for interruptible and dynamic (aka not following any predefined curve from the CSS transition) animations, right? Is there a gain if you precompute the values and the user interrupts and makes you recompute everything that remains?

4. I wish render was faster!. Though I'm not sure how much React 0.13/0.14 optimizations will help you here. You can try by manually lifting the components to a higher scope and rendering those references. It's about the same thing.

5. Haven't checked the code but for nested components, are you doing a single pass for all the `setState`s or are you `setState`ing the owner, then the child, then the grandchildren, etc.?

**Comment by natew** [comment]
1. I'm using the [parent-based context patch here](https://github.com/reapp/reapp-ui/blob/9c0bb1a3ee947423f0bc839309b8feb31236331a/lib/contextPatch.js), actually I needed it in order for animations to work properly, it was a big help. I was using a simple object store before, but that had problems with nested animations because it didn't work inside the react tree.

2. I'm using shouldComponentUpdate to block out all the stuff that isn't animating, but given the animation it still runs through a few levels. The main example is the [iOS style swipe back view seen here](http://gfycat.com/OrnateOrneryAcornwoodpecker) (it's an old demo). In that example you have this (pseudo-code):

```
<ViewList>
  <View>
    <TitleBar><Button><Icon backarrow> Back</Button></TitleBar>
    <StaticContainer>
      <ViewContents../>
    </StaticContainer>
  </View>

  <View>...</View>
</ViewList>
```

Where the `ViewList` handles a `step` property that defines the current step of the animation, and passes an `index` down to views. You can see more docs on [how animations work here](http://reapp.io/docs-animations.html).

But basically, the TitleBar -> Button -> Icon is necessary because the TitleBars move left, as well as the Button, but the Icons move right (to have the effect of staying still). So it's inherently a nested animation.

3. For me it would be two ways, the first being the one you describe ("transpiling" the animation to CSS and running it in CSS). The other option is to just memoize the output of the JS animation in a worker thread or just on componentDidMount. Basically to avoid having to do the actual calculation of the animation while it's running and instead just grab the output values that were pre-computed. This keeps everything in JS but given the slowness *seems* to be coming from React batched output it may not do much.

As for the former (CSS keyframe generation), this would be a definite win in performance and your keyframe generation in head is exactly what I was thinking *but* it does add a lot more complexity. Because those nested components are doing things programmatically now based on their animation state (off screen, animating, on screen). I think though for the case where a user isn't directly interacting though it still has a big benefit and is worthwhile in the long run.

4. I was thinking 0.14 would make it fast because the <TitleBar>, <Button>  and <Icon> elements all have a number of nodes that *aren't* animated, so React could save time on each frame not having to re-run that JS.

5. Yep, single pass on setstate in the grandparent and pass it down through context. In fact, it's pretty fast. Only in this single example where there's multiple animations nested deeply does it start to affect, and only on older mobile browsers. I landed another optimization using a fake box-shadow that sped it up more but on on my old Android device it's still laggy.

I really appreciate the detailed reply! I think I can live with the performance for now, and if I get time will explore the keyframe generation. Also looking forward to 0.14 to see how that helps.

A final thing, I tend to get lost when profiling React because most of the time is spent in the batched update stuff but it's hard to see exactly which elements are causing the most time there.

**Comment by nolimits4web** [comment]
@natew 
> I pushed up a new version of reapp-ui 0.11.13 that uses a separate shadow div rather than box-shadow. I see nicely improved performance. Also built a new version of Kitchen Sink that uses it. Simplifies quite a few things!

> On my old android phone though it's still slow. Need to get an iPhone 5 to test on as well which I'm in the process of getting.

On iOS it is now as smooth as silk :+1:

**Comment by natew** [comment]
@nolimits4web Swiper looks amazing. Shocked I hadn't seen it until now. How easy would it be to drop in for [Zynga Scroller](https://github.com/zynga/scroller)? I like being able to pass back handleScroll and get the raw x,y coordinates.

Scroller is nice but API is bad and speed could be better (I think). One big thing I want is to be able to change animation speed dynamically so when you press forward it takes 450ms, but backward takes 350ms. Not a hard change in Scroller but an example of something I need to change with it.

**Comment by nolimits4web** [comment]
@natew thanks, yes, it is the best one :) I am not really sure that I understood you question right. If you mean to replace Scroller with Swiper, then it is not a good idea, as Swiper was designed as highly configurable and flexible carousel, but it does not intended to be used as just content scroller, and will not work good for this purpose. But if you use Scroller as carousel, then sure, Swiper will do this job better, and yes, it allows to change animation speed dynamically

**Comment by kdar** [comment]
I tried the kitchen sink demo on a samsung note4 and android 5.0.1, and screen transitions are laggy. TouchstoneJS feels really snappy on screen transitions.

**Comment by mbrookes** [comment]
TouchstoneJS uses CSS transitions which are hardware accelerated, but
aren't realtime - Reapp uses touch/physics to let the user control
transition speed. Not saying it should lag on Android, but it's not really
a fair comparison.
